# Generated by Django 5.1.1 on 2024-11-06 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcion',
            options={'verbose_name': 'Función', 'verbose_name_plural': 'Funciones'},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='rolfuncion',
            options={'verbose_name': 'Rol-Función', 'verbose_name_plural': 'Roles-Funciones'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='usuariorol',
            options={'verbose_name': 'Usuario-Rol', 'verbose_name_plural': 'Usuarios-Roles'},
        ),
        migrations.AlterUniqueTogether(
            name='rolfuncion',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='usuariorol',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='rol',
            name='funciones',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='pass_field',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='funcion',
            name='id',
            field=models.AutoField(db_column='idFunciones', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rol',
            name='id',
            field=models.AutoField(db_column='idRoles', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rolfuncion',
            name='funcion',
            field=models.ForeignKey(db_column='Funciones_idFunciones', on_delete=django.db.models.deletion.CASCADE, to='log.funcion'),
        ),
        migrations.AlterField(
            model_name='rolfuncion',
            name='id',
            field=models.AutoField(db_column='idRolesFunciones', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rolfuncion',
            name='rol',
            field=models.ForeignKey(db_column='Roles_idRoles', on_delete=django.db.models.deletion.CASCADE, to='log.rol'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.AutoField(db_column='idUsuarios', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='usuariorol',
            name='id',
            field=models.AutoField(db_column='idUsuariosRoles', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuariorol',
            name='rol',
            field=models.ForeignKey(db_column='Roles_idRoles', on_delete=django.db.models.deletion.CASCADE, to='log.rol'),
        ),
        migrations.AlterField(
            model_name='usuariorol',
            name='usuario',
            field=models.ForeignKey(db_column='Usuarios_idUsuarios', on_delete=django.db.models.deletion.CASCADE, to='log.usuario'),
        ),
        migrations.AddIndex(
            model_name='rolfuncion',
            index=models.Index(fields=['funcion'], name='rf_funcion_idx'),
        ),
        migrations.AddIndex(
            model_name='rolfuncion',
            index=models.Index(fields=['rol'], name='rf_rol_idx'),
        ),
        migrations.AddIndex(
            model_name='usuariorol',
            index=models.Index(fields=['usuario'], name='ur_usuario_idx'),
        ),
        migrations.AddIndex(
            model_name='usuariorol',
            index=models.Index(fields=['rol'], name='ur_rol_idx'),
        ),
        migrations.AlterModelTable(
            name='funcion',
            table='Funciones',
        ),
        migrations.AlterModelTable(
            name='rol',
            table='Roles',
        ),
        migrations.AlterModelTable(
            name='rolfuncion',
            table='RolesFunciones',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='Usuarios',
        ),
        migrations.AlterModelTable(
            name='usuariorol',
            table='UsuariosRoles',
        ),
    ]
